version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/my-pet-life
    overwrite: yes
permissions:
  - object: /home/ubuntu/my-pet-life
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu