version: 0.0
os: linux

files:
  - source: / # CodeDeploy가 다운받을 경로 (/ : 전체 파일 다운)
    destination: /home/ubuntu/my-pet-life # ec2 서버에서 어느 경로에 해당 코드를 저장할지
permissions:
  - object: /home/ubuntu/my-pet-life
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user