spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: #입력
    username: root
    password: #입력

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        # 1. 서비스 제공자에 대한 정보
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

        # 2. 클라이언트를 식별하기 위한 정보
        registration:
          kakao:
            client-id: 587183b7a230a0d57f3a8851b6118c49
            client-secret: esiLrz4s3oMl7nX726quDsThILTH9S6f
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: aaaaabbbbbcccccddddeeeeffffgggghhhhiiiijjj

# springdoc, swagger3 설정
springdoc:
  packages-to-scan: com.example.mypetlife.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

naver-cloud-sms:
  accessKey : W5ApII2lReyzXR3lFhwx
  secretKey : svXItz8F1r7fRo9AkuhqJZ616R0jzdD5jsZvubO4
  serviceId : ncp:sms:kr:264202430202:my-pet-life
  senderPhone : #입력