# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
                
    - name: Set Yml
      uses: getsentry/action-release@v1
      env:
        DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }} 
        DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }} 
        DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }} 
        KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }} 
        KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }} 
        KAKAO_REDIRECT_URI: ${{ secrets.KAKAO_REDIRECT_URI }} 
        JWT_SECRET: ${{ secrets.JWT_SECRET }} 
        NAVER_CLOUD_SMS_ACCESS_KEY: ${{ secrets.NAVER_CLOUD_SMS_ACCESS_KEY }}
        NAVER_CLOUD_SMS_SECRET_KEY: ${{ secrets.NAVER_CLOUD_SMS_SECRET_KEY }}
        NAVER_CLOUD_SMS_SERVICE_ID: ${{ secrets.NAVER_CLOUD_SMS_SERVICE_ID }}
        NAVER_CLOUD_SMS_SENDER_PHONE: ${{ secrets.NAVER_CLOUD_SMS_SENDER_PHONE }}

    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
